# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\Projects\HystereticCurveProcess\ui\WinHelp.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WinHelp(object):
    def setupUi(self, WinHelp):
        WinHelp.setObjectName("WinHelp")
        WinHelp.resize(737, 813)
        WinHelp.setMinimumSize(QtCore.QSize(422, 0))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        WinHelp.setFont(font)
        WinHelp.setWindowTitle("帮助文档")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/资源/logo.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        WinHelp.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(WinHelp)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(WinHelp)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 717, 755))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        self.textBrowser.setFont(font)
        self.textBrowser.setObjectName("textBrowser")
        self.horizontalLayout_2.addWidget(self.textBrowser)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton = QtWidgets.QPushButton(WinHelp)
        self.pushButton.setMinimumSize(QtCore.QSize(100, 30))
        self.pushButton.setMaximumSize(QtCore.QSize(100, 30))
        self.pushButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton.setAutoDefault(False)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(WinHelp)
        self.pushButton.clicked.connect(WinHelp.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(WinHelp)

    def retranslateUi(self, WinHelp):
        _translate = QtCore.QCoreApplication.translate
        self.textBrowser.setHtml(_translate("WinHelp", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'微软雅黑\',\'微软雅黑\'; font-size:20pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\'; font-size:9pt;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\'; font-size:26pt;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:26pt;\">滞回曲线处理软件</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:26pt;\">帮助文档</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\'; font-size:26pt;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-weight:600;\">1 功能介绍</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:10pt; font-weight:600;\"> </span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:16pt;\">    该程序可用于对滞回曲线进行处理，主要功能包括：删除重复点、识别位移序列的卸载点、数据密度扩充、对位移序列进行单调化、曲线平滑、绘制骨架曲线点、计算滞回曲线的耗能指标、滞回曲线分圈。</span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\'; font-size:16pt;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-weight:600;\">2. 使用方法</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-weight:600;\">  </span><span style=\" font-family:\'SimSun\'; font-size:16pt;\">程序共包括8个窗口，每在一个窗口完成对应的操作后需点击右下方的下一步按钮，才能将数据传递至下一个窗口，点击上一步按钮则返回上一个窗口。</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:10pt; font-weight:600;\"> </span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:16pt; font-weight:600;\">（1）导入数据</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:16pt;\">    程序通过导入.txt文件来读取待处理的滞回曲线数据，支持单独导入和合并导入。若选择单独导入，位移或力数据应单独一列存放在.txt文件中，若选择合并导入，则.txt文件应包含两列数据，分别对应位移和力，建议直接从excel复制。</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:16pt;\">    对于位移序列，建议通过“反转位移序列”复选框将位移序列的开头部分设置为递增。</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:16pt;\">    用户还可导入附加数据，附加数据会随滞回曲线处理过程中一并处理，软件在对滞回曲线进行删除重复点、位移序列单调化、数据密度扩充、滞回环分圈、提取骨架曲线时，附加数据会随之进行增删操作。实际应用中，附加数据可以是除滞回曲线外的位移、应变、温度、压力等数据。导入的附加数据应保证长度与滞回曲线一致，否则无法导入。</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:16pt; font-weight:600;\">（2）删除重复点</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:16pt;\">    若在试验加载过程中有停顿，则滞回曲线会产生大量重复点，程序可通过位移序列判断位移重复点并删除，减小数据量。</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:16pt; font-weight:600;\">（3）识别位移卸载点</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:16pt;\">    位移卸载点指加载过程中每一圈滞回环位移达到最大值或最小值的点，识别位移的卸载点是进行后续处理的前提，程序通过自适应滑动窗口来识别位移卸载点，用户可拖动两个滑块来调整起始和终止滑动窗口的宽度，直至图中所标识出的卸载点全部识别正确为止，若拖动滑块仍无法正确识别卸载点，可手动删除。根据卸载点的实时识别情况，用户可根据以下方法来调整滑块位置：若位移序列前半部分的卸载点有遗漏，可减小起始宽度；若位移序列前半部分的卸载点有多余，可增大起始宽度；若位移序列后半部分的卸载点有遗漏，可减小终止宽度；若位移序列后半部分的卸载点有多余，可增大终止宽度。</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:16pt;\">    注：应保证所有的位移卸载点均识别正确才进行下一步操作，否则后续步骤的处理结果可能会有误。</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:16pt; font-weight:600;\">（4）数据密度扩充&amp;单调化</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:16pt;\">    滞回曲线可能会由于加载或测量装置的误差而产生局部的小幅卸载-再加载现象，如果作为位移时程用于有限元计算时输入，则可能会导致一些不必要的问题。因此，程序会基于第（3）步所识别的位移卸载点结果自动对曲线进行单调化处理，即对于相邻两个卸载点之间的数据，位移序列只允许单调递增或递减，不满足的数据点将被删除。</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:16pt;\">    此外，用户可指定最小位移增量值，当滞回曲线中每两个相邻点的位移差大于该值时，程序会自动在该两点间做线性差值，使数据满足最小密度要求。</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:16pt; font-weight:600;\">（5）曲线平滑</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:16pt;\">    程序可以采用简单移动窗口平均算法对滞回曲线的力序列进行平滑，若用户选择进行曲线平滑，可输入窗口的宽度值，并查看平滑前后的力序列曲线对比。</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:16pt; font-weight:600;\">（6）骨架点及耗能指标</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:16pt;\">    程序会自动提取骨架点及计算滞回曲线的耗能特征，包括单圈耗能、累积耗能和等效黏滞阻尼系数。其中骨架点的确定方法包括最大位移、最大力和最大位移&amp;最大力（如图1）。其中，最大位移和最大力分别指采用每一圈滞回环的最大位移或最大力所对应的数据点作为骨架点（注：骨架点不等于骨架曲线，骨架曲线需要根据指定滞回圈数来确定，见第（7）条）；基于最大位移&amp;最大力的骨架点确定方法指将滞回环的最大位移和最大力进行归一化后，选取位移和力的平方和最大的数据点作为骨架点（等价于以原点为圆心的滞回环外切圆与滞回环的交点）。若构件破坏而导致最后一圈滞回环存在明显的退化现象，用户可选择不考虑最后一圈滞回环。</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/资源/骨架点确定方法.png\" /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/资源/骨架点确定方法-2.png\" /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:16pt;\">图1 骨架点的确定方法</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:16pt;\">    在计算等效黏滞阻尼系数时，需要根据等效弹性弹簧的刚度计算等效弹性应变能，软件提供三种确定方法等效弹性弹簧的刚度，分别为根据该滞回环上的最大力所在点、最大位移所在点、或最大位移-最大力点来确定该刚度（如图2）。</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">            <img src=\":/资源/等效弹性弹簧.png\" /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:16pt;\">图2 等效弹性弹簧的确定方法</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\'; font-size:16pt;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:16pt; font-weight:600;\">（7）骨架曲线&amp;退化曲线</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:16pt; font-weight:600;\">    </span><span style=\" font-family:\'SimSun\'; font-size:16pt;\">为了在滞回曲线中提取骨架曲线，用户需首先指定用于提取骨架曲线的滞回圈数，程序提供几种默认的滞回圈数方案（即常用方案），如采用第1圈、第4圈、第7圈的滞回环来提取骨架曲线（对应于常用方案(1)），如常用方案仍无法正确满足用于需求，可手动输入滞回圈数（即手动指定），用户手动输入用于提取骨架曲线的滞回圈数，并以空格间隔即可。</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:16pt;\">    在确定滞回圈数后，需点击“添加到方案”按钮，程序才会记录该方案。</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:16pt; font-weight:600;\">（8）查看各圈滞回环</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:16pt;\">    用户可查看各圈滞回环对应的滞回曲线，以及各圈滞回环的统计指标。</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:16pt; font-weight:600;\">（9）结果输出</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:16pt;\">    用户可查看并导出滞回曲线的处理及分析结果数据，数据将汇总于“数据汇总.xlxs”中，并单独生成几个.txt文件以存放各类数据。</span></p></body></html>"))
        self.pushButton.setText(_translate("WinHelp", "确认"))
import resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WinHelp = QtWidgets.QWidget()
    ui = Ui_WinHelp()
    ui.setupUi(WinHelp)
    WinHelp.show()
    sys.exit(app.exec_())
